version: '3'

services:
  app:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["python", "-m", "streamlit", "run", "app/main.py"]
